"""initial migration with Flask-Security-Too and standardized schema

Revision ID: b8e1f024803f
Revises: 
Create Date: 2026-07-27 22:22:18.678891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8e1f024803f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.alter_column('fs_uniquifier',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.create_unique_constraint('uq_admin_users_fs_uniquifier', ['fs_uniquifier'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_admin_users_fs_uniquifier', type_='unique')
        batch_op.alter_column('fs_uniquifier',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###
